### ISSUE TITLE
Merge props returned from function with other props in pattern definition

### ISSUE THREAD

**Issue by whastings** [eoneill/eyeglass-restyle#2]
Currently, if I have code like below, the function's returned props will be tacked on after the rest of the props in the definition, preventing the definition from overriding any of the function's props:

```scss
@function func-that-returns-color() {
  @return (color: blue);
}
restyle-define(foo, (
  restyle-function(func-that-returns-color): (),
  color: red
));

.foo {
  @include restyle(foo);
}

// Output:
.foo {
  color: red;
  color: blue;
}
```

It would be nice if the output of the function was merged in instead of tacked on, with later props in the definition overriding props in the function. That way, the output would instead be `.foo { color: red; }`.
